import React,{Componet, Component} from 'react'
import {Spin,Table} from 'antd'
import Detail from './detail'
const data=[{
    id:'1',
    periodType:'周',
    period:'10',
    beginTime:'2019-01-01',
    endTime:'2019-01-01',
    process:'单晶体配置',
    subtotal:'360m³',
    Nimetal:'7.5',
    Cometal:'7.1',
    Mnmetal:'7.6'
},{
    id:'2',
    periodType:'周',
    period:'10',
    beginTime:'2019-01-01',
    endTime:'2019-01-01',
    process:'单晶体配置',
    subtotal:'360m³',
    Nimetal:'7.5',
    Cometal:'7.1',
    Mnmetal:'7.6'
}]
class StatisticDone extends Component{//已统计
    constructor(props){
        super(props);
        this.state={
            loading:false,
            data:data
        }
        this.columns=[{
            title:'序号',
            dataIndex:'id',
            key:'id'
        },{
            title:'周期类型',
            dataIndex:'period',
            key:'period'
        },{
            title:'期数',
            dataIndex:'LineName',
            key:'LineName'
        },{
            title:'开始时间',
            dataIndex:'startTime',
            key:'startTime'
        },{
            title:'结束时间',
            dataIndex:'endTime',
            key:'endTime'
        },{
            title:'过程工序',
            dataIndex:'process',
            key:'process'
        },{
            title:'小计值',
            dataIndex:'subtotal',
            key:'subtotal'
        },{
            title:'Ni金属量(T)',
            dataIndex:'Nimetal',
            key:'Nimetal'
        },{
            title:'Co金属量(T)',
            dataIndex:'Cometal',
            key:'Cometal'
        },{
            title:'Mn金属量(T)',
            dataIndex:'Mnmetal',
            key:'Mnmetal'
        },{
            title:'操作',
            dataIndex:'operation',
            key:'operation',
            render:(text,record)=>{
                return(
                    <Detail record={record} url={this.props.url} processDetailId={record.id}/>
                )
            }
        }]
    }

    render(){
        return(
            <div>
                <Spin spinning={this.state.loading} wrapperClassName='rightContent-Div'>
                    <Table
                    rowKey={record=>record.id}
                    dataSource={this.props.dataStatistic}
                    columns={this.columns}
                    size='small'
                    bordered/>
                </Spin>
            </div>
        );
    }
}
export default StatisticDone